# dhcpd.conf
option domain-name "varilongo.com";
option domain-name-servers 192.168.2.10, 192.168.2.11;

default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;

failover peer "var-failover" {
         secondary;
         address 192.168.2.11;
         port 520;
         peer address 192.168.2.10;
         peer port 519;
         max-response-delay 60;
         max-unacked-updates 10;
       }

subnet 192.168.2.0 netmask 255.255.255.0 {
  option routers 192.168.2.1;
   pool{
    failover peer "var-failover";
    range 192.168.2.100 192.168.2.250;
   }
}
subnet 192.168.3.0 netmask 255.255.255.0 {
  option routers 192.168.3.1;
   pool{
    failover peer "var-failover";
    range 192.168.3.100 192.168.3.250;
   }

}
subnet 192.168.4.0 netmask 255.255.255.0 {
  option routers 192.168.4.1;
   pool{
    failover peer "var-failover";
    range 192.168.4.100 192.168.4.250;
   }
  host SRV-WEB {
    hardware ethernet 00:0c:29:00:04:51;
    fixed-address 192.168.4.10;
  }
}
subnet 192.168.5.0 netmask 255.255.255.0 {
 option routers 192.168.5.1;
   pool{
    failover peer "var-failover";
    range 192.168.5.100 192.168.5.250;
   }
}
